cp/manageguest/analytics/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from .views import dashboard,urldetail

app_name = 'analytics'

urlpatterns = [
    url(r'^$', dashboard, name='home'),
    url(r'^(?P<username>[-\w]+)/$', urldetail, name='detail'),
]

cp/manageguest/guest/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from .views import dashboard

urlpatterns = [
    url(r'^$', dashboard, name='home'),
]

cp/manageguest/manageguest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include

urlpatterns = [
        path('admin/', admin.site.urls),
        url(r'^guest/',include('guest.urls')),
]

cp/manageguest/analytics/models.py
from django.db import models

# Create your models here.

cp/manageguest/analytics/views.py
from datetime import datetime, timedelta
from django.db.models import Count
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from guest.models import Userbehavior


# Create your views here.
def dashboard(request):
    if 'days' in request.GET:
        get_days = int(request.GET['days'])
    else:
        get_days = 7

    one_week_ago = datetime.today() - timedelta(get_days)
    uni_url = Userbehavior.objects.filter(datetime__gte=one_week_ago).values('url').distinct().count()
    uni_visitors = Userbehavior.objects.filter(datetime__gte=one_week_ago).values('username').distinct().count()
    uni_devices = Userbehavior.objects.filter(datetime__gte=one_week_ago).values('macaddress').distinct().count()
    uni_dstport = Userbehavior.objects.filter(datetime__gte=one_week_ago).values('dstport').distinct().count()
    top_10_users = Userbehavior.objects.filter(datetime__gte=one_week_ago).values('username').annotate(total=Count('username')).order_by('-total')[:10]
    top_10_urls = Userbehavior.objects.filter(datetime__gte=one_week_ago).values('url').annotate(total=Count('url')).order_by('-total')[:11]
    context = {
        'unique_urls' : uni_url,
        'unique_visitors' : uni_visitors,
        'unique_devices' : uni_devices,
        'unique_dstports' : uni_dstport,
        'top10users' : top_10_users,
        'top10urls' : top_10_urls,
    }
    return render(request, "analytics/dashboard.html", context)


def urldetail(request,username):
    if 'days' in request.GET:
        get_days = int(request.GET['days'])
    else:
        get_days = 7

    one_week_ago = datetime.today() - timedelta(get_days)
    user = username
    urllist = Userbehavior.objects.filter(datetime__gte=one_week_ago,username=user).values('url').distinct()

    page = request.GET.get('page', 1)

    paginator = Paginator(urllist,10)

    try:
        urls = paginator.page(page)
    except PageNotAnInteger:
        urls = paginator.page(1)
    except EmptyPage:
        urls = paginator.page(paginator.num_pages)

    context = {
        'urllist' : urls,
    }
    return render(request,"analytics/userdetails.html",context)

cp/manageguest/analytics/templates/analytics/dashboard.html
{% extends "base.html" %}

{% block content %}

	<DIV class="container">
		<DIV class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="display:flex;margin: 10px 0 10px 0;">
			<div style="flex:10;"></div>
			<div class="btn-group text-right" style="flex:2;">
  				<button type="button" class="btn btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    				Select data
 				</button>
 			<div class="dropdown-menu">
				<a class="dropdown-item" href="/analytics/?days=1">Past day</a>
  				<a class="dropdown-item" href="/analytics/?days=7">Past 7 days</a>
  				<a class="dropdown-item" href="/analytics/?days=30">Past 30 days</a>
			</div>
  			</div>
			</div>
		</DIV>
		<DIV class="row">
		<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">	
				<div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
  					<div class="card-body">
    					<h5 class="card-title">Unique Visitors</h5>
					<h1 class="card-text">{{ unique_visitors }}</h1p>
  					</div>
				</div>
		</div>
		<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                <div class="card text-white bg-secondary mb-3" style="max-width: 18rem;">
                                        <div class="card-body">
                                        <h5 class="card-title">Unique Devices</h5>
                                        <h1 class="card-text">{{ unique_devices }}</h1p>
                                </div>
                                </div>
                </div>
		<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
                                        <div class="card-body">
                                        <h5 class="card-title">Unique URLs</h5>
                                        <h1 class="card-text">{{ unique_urls }}</h1p>
                                </div>
                                </div>
                </div>
		<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
                                        <div class="card-body">
                                        <h5 class="card-title">Unique Services</h5>
                                        <h1 class="card-text">{{ unique_dstports }}</h1p>
                                </div>
                                </div>
                </div>
		</DIV>
		<DIV class="row" style="padding-top:50px;padding-bottom:50px">
		<DIV class="col-lg-4 col-md-4 col-sm-6 col-xs-6 demo">
                        <DIV class="demo-container">
                                <DIV class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="chart0" style="height:400px;">
		<script type="text/javascript">
Highcharts.chart('chart0', {
    chart: {
        type: 'area'
    },
    accessibility: {
        description: 'An area chart compares the nuclear stockpiles of the USA and the USSR/Russia between 1945 and 2017. The number of nuclear weapons is plotted on the Y-axis and the years on the X-axis. The chart is interactive, and the year-on-year stockpile levels can be traced for each country. The US has a stockpile of 6 nuclear weapons at the dawn of the nuclear age in 1945. This number has gradually increased to 369 by 1950 when the USSR enters the arms race with 6 weapons. At this point, the US starts to rapidly build its stockpile culminating in 32,040 warheads by 1966 compared to the USSR’s 7,089. From this peak in 1966, the US stockpile gradually decreases as the USSR’s stockpile expands. By 1978 the USSR has closed the nuclear gap at 25,393. The USSR stockpile continues to grow until it reaches a peak of 45,000 in 1986 compared to the US arsenal of 24,401. From 1986, the nuclear stockpiles of both countries start to fall. By 2000, the numbers have fallen to 10,577 and 21,000 for the US and Russia, respectively. The decreases continue until 2017 at which point the US holds 4,018 weapons compared to Russia’s 4,500.'
    },
    title: {
        text: 'Online users & devices by AP'
    },
    subtitle: {
        text: 'last 12 months'
    },
    xAxis: {
        allowDecimals: false,
        labels: {
            formatter: function () {
                return this.value; // clean, unformatted number for year
            }
        }
    },
    yAxis: {
        title: {
            text: 'Nuclear weapon states'
        },
        labels: {
            formatter: function () {
                return this.value / 1000 + 'k';
            }
        }
    },
    tooltip: {
        pointFormat: '{series.name} had stockpiled <b>{point.y:,.0f}</b><br/>warheads in {point.x}'
    },
    plotOptions: {
        area: {
            pointStart: 1940,
            marker: {
                enabled: false,
                symbol: 'circle',
                radius: 2,
                states: {
                    hover: {
                        enabled: true
                    }
                }
            }
        }
    },
    series: [{
        name: 'USA',
        data: [
            null, null, null, null, null, 6, 11, 32, 110, 235,
            369, 640, 1005, 1436, 2063, 3057, 4618, 6444, 9822, 15468,
            20434, 24126, 27387, 29459, 31056, 31982, 32040, 31233, 29224, 27342,
            26662, 26956, 27912, 28999, 28965, 27826, 25579, 25722, 24826, 24605,
            24304, 23464, 23708, 24099, 24357, 24237, 24401, 24344, 23586, 22380,
            21004, 17287, 14747, 13076, 12555, 12144, 11009, 10950, 10871, 10824,
            10577, 10527, 10475, 10421, 10358, 10295, 10104, 9914, 9620, 9326,
            5113, 5113, 4954, 4804, 4761, 4717, 4368, 4018
        ]
    }, {
        name: 'USSR/Russia',
        data: [null, null, null, null, null, null, null, null, null, null,
            5, 25, 50, 120, 150, 200, 426, 660, 869, 1060,
            1605, 2471, 3322, 4238, 5221, 6129, 7089, 8339, 9399, 10538,
            11643, 13092, 14478, 15915, 17385, 19055, 21205, 23044, 25393, 27935,
            30062, 32049, 33952, 35804, 37431, 39197, 45000, 43000, 41000, 39000,
            37000, 35000, 33000, 31000, 29000, 27000, 25000, 24000, 23000, 22000,
            21000, 20000, 19000, 18000, 18000, 17000, 16000, 15537, 14162, 12787,
            12600, 11400, 5500, 4512, 4502, 4502, 4500, 4500
        ]
    }]
});
		</script>
				</DIV>
			</DIV>
		</DIV>


		<DIV class="col-lg-4 col-md-4 col-sm-6 col-xs-6 demo">
			<DIV class="demo-container">
				<DIV class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="chart1" style="height:400px;">
				<script type="text/javascript">
					Highcharts.chart('chart1', {

    chart: {
        scrollablePlotArea: {
            minWidth: 700
        }
    },

    data: {
        csvURL: 'https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/analytics.csv',
        beforeParse: function (csv) {
            return csv.replace(/\n\n/g, '\n');
        }
    },

    title: {
        text: 'Sessions'
    },

    subtitle: {
        text: 'last 12 months'
    },

    xAxis: {
        tickInterval: 7 * 24 * 3600 * 1000, // one week
        tickWidth: 0,
        gridLineWidth: 1,
        labels: {
            align: 'left',
            x: 3,
            y: -3
        }
    },

    yAxis: [{ // left y axis
        title: {
            text: null
        },
        labels: {
            align: 'left',
            x: 3,
            y: 16,
            format: '{value:.,0f}'
        },
        showFirstLabel: false
    }, { // right y axis
        linkedTo: 0,
        gridLineWidth: 0,
        opposite: true,
        title: {
            text: null
        },
        labels: {
            align: 'right',
            x: -3,
            y: 16,
            format: '{value:.,0f}'
        },
        showFirstLabel: false
    }],

    legend: {
        align: 'left',
        verticalAlign: 'top',
        borderWidth: 0
    },

    tooltip: {
        shared: true,
        crosshairs: true
    },

    plotOptions: {
        series: {
            cursor: 'pointer',
            point: {
                events: {
                    click: function (e) {
                        hs.htmlExpand(null, {
                            pageOrigin: {
                                x: e.pageX || e.clientX,
                                y: e.pageY || e.clientY
                            },
                            headingText: this.series.name,
                            maincontentText: Highcharts.dateFormat('%A, %b %e, %Y', this.x) + ':<br/> ' +
                                this.y + ' sessions',
                            width: 200
                        });
                    }
                }
            },
            marker: {
                lineWidth: 1
            }
        }
    },

    series: [{
        name: 'All sessions',
        lineWidth: 4,
        marker: {
            radius: 4
        }
    }, {
        name: 'New users'
    }]
});

				</script>
				</DIV>
			</DIV>
		</DIV>
		<DIV class="col-lg-4 col-md-4 col-sm-6 col-xs-6 demo">
			<DIV class="demo-container">
				<DIV class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="servicechart">
				<script type="text/javascript">
				// Build the chart
				Highcharts.chart('servicechart', {
    					chart: {
        					plotBackgroundColor: null,
        					plotBorderWidth: null,
        					plotShadow: false,
        					type: 'pie'
    					},
    					title: {
        					text: 'Services'
    					},
					subtitle: {
						text: 'last 12 months'
					},
    					tooltip: {
        					pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    					},
    					plotOptions: {
        					pie: {
            					allowPointSelect: true,
            					cursor: 'pointer',
            					dataLabels: {
                					enabled: false
            					},
            					showInLegend: true
        				}
    					},
    					series: [{
        					name: 'Brands',
        					colorByPoint: true,
        					data: [{
            					name: 'Chrome',
            					y: 61.41,
            					sliced: true,
            					selected: true
        					}, {
            					name: 'Internet Explorer',
            					y: 11.84
        					}, {
            					name: 'Firefox',
            					y: 10.85
        					}, {
            					name: 'Edge',
            					y: 4.67
        					}, {
            					name: 'Safari',
            					y: 4.18
        					}, {
            					name: 'Other',
            					y: 7.05
        					}]
    					}]
					});
				</script>
                        	</DIV>
			</DIV>
		</DIV>
		</DIV>
		<DIV class="container">
		<DIV class="row">
		<DIV class="col-6">
		<table class="table table-bordered">
		  <thead>
   			<tr>
      			<th scope="col">#</th>
      			<th scope="col">Top 10 sites</th>
     			<th scope="col">Hits</th>
    			</tr>
  		</thead>
  		<tbody>
			{% for url in top10urls %}
			{% if url.url %}
   			<tr>
				<th scope="row">{{ forloop.counter|add:"-1" }}</th>
			<td>
				{% if url.dstport == "443" %}
				<a href="https://{{ url.url }}">{{ url.url }}</a>
				{% else %}
				<a href="http://{{ url.url }}">{{ url.url }}</a>
				{% endif %}
			</td>

			<td>{{ url.total }}</td>
    			</tr>
			{% endif %}
			{% endfor %}
  		</tbody>
		</table>
		</DIV>


                <DIV class="col-6">
                <table class="table table-bordered">
                  <thead>
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col">Top 10 users</th>
                        <th scope="col">Connections</th>
                        </tr>
                </thead>
                <tbody>
                        {% for user in top10users %}
                        {% if user.username %}
                        <tr>
                        <th scope="row">{{ forloop.counter }}</th>
			<td><a href="{% url 'analytics:detail' user.username %}">{{ user.username }}</a></td>
                        <td>{{ user.total }}</td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                </tbody>
                </table>
                </DIV>
		</DIV>
		</DIV>


	</DIV>

    
{% endblock %}

cp/manageguest/analytics/templates/analytics/userdetails.html
{% extends "base.html" %}
{% block content %}
<DIV class="container">
                <DIV class="row">
                <DIV class="col-12">
                <table class="table table-bordered">
                  <thead>
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col">Site</th>
                        </tr>
                </thead>
                <tbody>
                        {% for url in urllist %}
                        {% if url.url %}
                        <tr>
				<th scope="row">{{forloop.counter}}</th>
                        <td>{{ url.url }}</td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                </tbody>
                </table>
                </DIV>
		<DIV class="col-12">
			{% if urllist.has_other_pages %}
			<nav aria-label="Page navigation example">
  				<ul class="pagination justify-content-center">
					{% if urllist.has_previous %}
    						<li class="page-item">
      						<a class="page-link" href="?page={{ urllist.previous_page_number }}" aria-label="Previous">
        					<span aria-hidden="true">&laquo;</span>
        					<span class="sr-only">Previous</span>
      						</a>
						</li>
					{% else %}
						<li class="disabled"><span>&laquo;</span></li>
					{% endif %}
					{% for i in urllist.paginator.page_range %}
					   {% if i <= urllist.number|add:3 and i >= urllist.number|add:-3 %}
						{% if i == urllist.number %}
						<li class="page-item active"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
						{% else %}
						 <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
						 {% endif %}
					   {% endif %}
					{% endfor %}
					{% if urllist.has_next %}
      					<a class="page-link" href="?page={{ urllist.next_page_number }}" aria-label="Next">
        				<span aria-hidden="true">&raquo;</span>
        				<span class="sr-only">Next</span>
      					</a>
    					</li>
					{% else %}
					<li class="disabled"><span>&laquo;</span></li>
					{% endif %}
  				</ul>
			</nav>
			{% endif %}
		</DIV>
</DIV>
{% endblock %}